services:
  livestreamrecorderservice:
    container_name: livestreamrecorderservice
    image: ghcr.io/recorder-moe/livestreamrecorderservice:latest
    user: "1654:0"
    env_file:
      - .env
    volumes:
      - ~/.kube/config:/.kube/config
    #  - ./appsettings.json:/app/appsettings.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
